### ISSUE TITLE
Create a book for online documentation

### ISSUE THREAD

**Issue by jeffa5** [automerge/automerge-rs#100]
The Rust code documentation will be good to have and useful when implementing things in Rust but I think there is still a need for wider Automerge documentation (with rust specific code examples). 

I'll propose using [mdbook](https://github.com/rust-lang/mdBook) as a typical example of documenting Rust projects more thoroughly.

**Comment by jkankiewicz** [comment]
@jeffa5, I've added documentation generation to the experimental C API in #275.

**Comment by jeffa5** [comment]
There is now the great [automerge website](https://automerge.org/) with documentation so I'll close this.
