### ISSUE TITLE
Does not work when using ECMAScript modules in nodejs

### ISSUE THREAD

**Issue by nemanja-tosic** [automerge/automerge-rs#110]
The backend is built for two targets: node (`wasm-pack build --target nodejs`) and bundler (i.e. webpack)  (`wasm-pack build --target bundler`).

The published version of the backend has a [subpath exports](https://nodejs.org/api/packages.html#packages_subpath_exports) field in the package.json with 2 conditional exports like so

```
"exports": {
    ".": { 
      "require": "./cjs/index.js",
      "default": "./mjs/index.js"
    }
  },
```

Node, starting from 13 something, supports ESM. If we were to use ESM and import automerge-backend-wasm, it would go to the "default" export, which is for a bundler. This fails.

The exports should be changed, at the bare minimum, into:

```
"exports": {
    ".": { 
      "node": "./cjs/index.js",
      "default": "./mjs/index.js"
    }
  },
```

Example repo: https://github.com/livingspec/automerge

Steps to reproduce:

1. yarn
2. yarn test:esm

Expected result: does not fail

**Comment by vedantroy** [comment]
Quick question: If we were to use ESM, wouldn't it still use the "node" key in the "exports" object. And the "node" key refers to a commonjs file, which is not ESM compatible?

**Comment by nemanja-tosic** [comment]
[You can import CommonJS from ESM](https://nodejs.org/api/esm.html#esm_interoperability_with_commonjs):

> An import statement can reference an ES module or a CommonJS module.

(automerge-backend-wasm being the CommonJS module, and the test package an ESM, in this scenario).

As per the [conditional exports](https://nodejs.org/api/packages.html#packages_conditional_exports) spec, it would use the node export in both cases:

> matches for any Node.js environment. Can be a CommonJS or ES module file

So putting both together should mean that the export will work with both CommonJS and ESM - which you can test by running the test script for both the export that's there now (require) and the suggested one (node).

**Comment by orionz** [comment]
Please try the new `automerge-wasm` npm package.  This should work in both commonjs and mjs.
