### ISSUE TITLE
Does not work in a webpack 5 worker

### ISSUE THREAD

**Issue by nemanja-tosic** [automerge/automerge-rs#111]
When importing the backend from a WebWorker in Webpack 5, all we get is an empty module. Upon some inspection, it appears that webpack is treating the index_js.bg file specially, i.e it removes all exports besides the ones needed for WASM, which means it removes all backend related exports.

We have managed to get around this problem by changing the index.js files as follows:

```
import "../build/mjs/index_bg.wasm";

export const init = backend.init;
export const applyChanges = backend.applyChanges;
export const applyLocalChange = backend.applyLocalChange;
export const getChanges = backend.getChanges;
export const getAllChanges = backend.getAllChanges;
export const getMissingDeps = backend.getMissingDeps;
export const getPatch = backend.getPatch;
export const load = backend.load;
export const clone = backend.clone;
export const free = backend.free;
export const getHeads = backend.getHeads;
export const loadChanges = backend.loadChanges;
export const save = backend.save;
export const decodeSyncMessage = backend.decodeSyncMessage;
export const decodeSyncState = backend.decodeSyncState;
export const encodeSyncMessage = backend.encodeSyncMessage;
export const encodeSyncState = backend.encodeSyncState;
export const generateSyncMessage = backend.generateSyncMessage;
export const initSyncState = backend.initSyncState;
export const receiveSyncMessage = backend.receiveSyncMessage;
```

Instead of 

```
import * as wasm from "./index_bg.wasm";
export * from "./index_bg.js";
```

Note that automerge-backend-wasm re-exports from index_bg.js which webpack apparently treats separately.

I have tried to set up an automated test for this, but had no luck in setting up a test environment for webpack, i might do that another day. Until then a test repo can be found here: https://github.com/livingspec/automerge

Steps to reproduce:

1. yarn
2. yarn dev
3. go to https://localhost:3000/worker_bug

Expected: the page should show all the backend functions
Actual: the page shows an empty object, meaning `import * as backend from 'automerge-backend-wasm'` came back empty

**Comment by orionz** [comment]
I just published a new package from the new codebase - `automerge-wasm` - please let me know if you have issues with the new package

**Comment by alexjg** [comment]
@nemanja-tosic is this still a problem for you?

**Comment by nemanja-tosic** [comment]
We currently do not use automerge, so i can't verify.
