### ISSUE TITLE
New encoding/decoding breaks downstream libraries.

### ISSUE THREAD

**Issue by johnfaucette** [automerge/automerge-rs#143]
The encoding::Error and decoding::Error are not added to AutomergeError so they cannot be caught by consuming libraries in general.

Here was my quick hack to fix this issue locally in (`automerge-backend/src/lib.rs`)
```rust
pub use encoding::Error as EncodingError;
pub use decoding::Error as DecodingError;
```

I don't know much about the structure of automerge-rs or rust in general, but it might make sense to take these up in the `errors.rs` file. Right now there is only the encoding::Error and decoding::Error from the external crates being considered, we need to be able to respond to the errors being thrown from the the encoding and decoding modules.

**Comment by jeffa5** [comment]
Thanks for the report @johnfaucette. We've applied the fix and should be on main now :)
