### ISSUE TITLE
`pred` should be sorted in encoded change

### ISSUE THREAD

**Issue by ept** [automerge/automerge-rs#145]
This issue was found by @endeavour42. The following two changes differ only in the order of the `preds` on the operation:

```js
{"actor": "f4d13a8a", "seq": 67, "startOp": 140, "time": 6207000, "message": "",
  "deps": ["3a1ebe64fdb4b442317e518e0a03238cbde72291394217e0954061588ca8c2e5"],
  "hash": "1fe5702c0d516dba1bf04847d4bcf64faedc22d6b00a389cb08ddf1da8d42fca",
  "ops": [
    {"obj": "_root", "key": "commonVar", "action": "set", "insert": false, "value": "4091494582",
     "pred": ["139@f4d13a8a", "139@37ea42f2"]}
  ]
}

{"actor": "f4d13a8a", "seq": 67, "startOp": 140, "time": 6207000, "message": "",
  "deps": ["3a1ebe64fdb4b442317e518e0a03238cbde72291394217e0954061588ca8c2e5"],
  "hash": "2c42aea2581b92b157a83c250e7f7a1cd3d528f651774555a996bb7eb6ed3339",
  "ops": [
    {"obj": "_root", "key": "commonVar", "action": "set", "insert": false, "value": "4091494582",
     "pred": ["139@37ea42f2", "139@f4d13a8a"]}
  ]
}
```

The binary format requires that `preds` appear in sorted order (in ascending Lamport timestamp order). The JS implementation does this sorting [here](https://github.com/automerge/automerge/blob/main/backend/columnar.js#L441), but it seems like the Rust implementation is not doing this sorting step. The correct encoded hash for both changes above should be `2c42aea2581b92b157a83c250e7f7a1cd3d528f651774555a996bb7eb6ed3339`.

**Comment by ept** [comment]
In fact, maybe we should have the decoder return an error if it encounters `pred` values that are not in ascending order. That would have helped catch this bug earlier.

**Comment by jeffa5** [comment]
Thanks for this bug report! I wonder if it should be a strict error if the predecessors aren't sorted. Does the js code rely on this fact somewhere?

**Comment by ept** [comment]
Yes, we should make it an error if the predecessors are not sorted. I'll do that on the JS side.

**Comment by ept** [comment]
See automerge/automerge#393
