### ISSUE TITLE
Ambiguous serialized keys

### ISSUE THREAD

**Issue by jeffa5** [automerge/automerge-rs#196]
From the serde proptests a change with a key `Map("0@")` serializes to `"0@"` and then gets parsed as `Seq(Id(0@))`.

I'm not sure if this has a fix on the JS side but it would be nice to keep keys being unrestricted. We could do some disambiguation in the parsing if we track the type of the parent object. Alternatively we could change the `key` to be `elem_id` for sequence types?

**Comment by alexjg** [comment]
I would really like to change `key` to `elem_id`, unfortunately I think this would be a pretty disruptive breaking change for JS so we'll probably need to do the object type based disambiguation.

**Comment by ept** [comment]
In what context is this? A little while ago I did [change the definition of operations in a change](https://github.com/automerge/automerge/commit/6fa8b5a5b9bbfb178750c629fc6107b30b9c35a3) so that list operations would use `elemId` while map operations would use `key`.

**Comment by jeffa5** [comment]
Thanks @ept I think it was just a bug in our deserialization.
