### ISSUE TITLE
Arbitrary structs with custom serialization

### ISSUE THREAD

**Issue by lehmanju** [automerge/automerge-rs#22]
Would it be possible to provide a frontend that works with arbitrary Rust structs? Maybe [treediff](https://docs.rs/treediff/4.0.0/treediff/index.html) could be helpful for this.

We would like to use Automerge for a project storing mostly coordinates and binary data. JSON isn't very suitable for us, hence we would like to use ordinary structs. These structs will be serializable to Cap'nProto which is structurally similar to JSON. Instead of providing an Automerge fronted for Cap'nProto, it should be possible to specify a trait that has to be implemented, comparing and serializing its data. Also, conflicts would have to be managed through a callback, I presume.

I should also mention that this project will run natively in Rust and is not associated with a webbrowser.

**Comment by LittleHuba** [comment]
Request is part of Xournal++ discussion just so you know the association.

**Comment by alexjg** [comment]
I am very interested in doing some kind of diff based library that works with arbitrary Rust structs. However, I don't think this belongs in the core automerge library because it won't be suitable for all usecases. I've sketched what I think such an API might look like here: https://gist.github.com/alexjg/c12eb15d509bbe4d68d5e80bc72cbeb4. I would be interested to hear what you think of this idea.

The main reason this wouldn't be appropriate for all usecases is that it requires traversing the entire tree of your data structure on every change. My current feeling is that the best approach here is to keep the frontend crate low level and allow building these kind of libraries on top of it in separate crates with their own lifecycle.

**Comment by lehmanju** [comment]
This looks great. I guess the only question is how a `LocalChange` would get serialized. Also it might be interesting to specify at which level values are atomic. You might have a big struct tree but even if an object could be partitioned further, one could be interested in keeping it as a single value.

Proxy objects for immutable values are always tricky. Maybe writing a trait and generating a corresponding struct is better than the other way around?

**Comment by lehmanju** [comment]
@alexjg Browsing the web I found this: https://www.youtube.com/watch?v=tmM756XZt20

While initially targeting GUIs, *moxie* seems to help with observing immutable data change. Maybe this could be helpful for a proxy object.

**Comment by orionz** [comment]
Maybe I don't understand - if your project is pure rust you can use the rust data structures for `ChangeRequest` and `Patch`.  JSON right now is only really used to pass those two structures to langauges other than Rust.

**Comment by orionz** [comment]
As for the C bindings, accessing the backend API from non-rust languages, or the WASM bindings, I'm currently serializing to JSON as a lowest common denominator.  If you're accessing the backend from a C++ app (or something similar) and need something more efficient I'd be happy to implement it.

**Comment by jeffa5** [comment]
I've had a go at creating some `derive` macros for converting to and from automerge values and written an associated `diff` and `Document`.

Its still very early stage but happy for any suggestions/reviews/contributions.

It would be awesome to have some sort of proxy for changes to keep the cost down and I might try and do the diff without converting it all to automerge Values first at some point.

https://github.com/jeffa5/automergeable/

**Comment by alexjg** [comment]
@jeffa5 This looks pretty fantastic. I'll dive into it in a bit, but it's pretty much exactly what I was imagining a macro driven diffing approach might look like!
