### ISSUE TITLE
create a new release

### ISSUE THREAD

**Issue by dvc94ch** [automerge/automerge-rs#220]
the last release was 18 months ago, maybe time for a new one.

**Comment by alexjg** [comment]
I've been waiting on the 1.0 release of the JS implementation which I believe is imminent.

**Comment by timfpark** [comment]
It seems like automerge has launched 1.0 - or at least 1.0.1-preview.6 is what is installed by default now...  Does it make sense to do a release here as well?

**Comment by alexjg** [comment]
We're working on a full rewrite in the `experiment` branch which has a much simpler API. I think we'll do a release once that's complete.

**Comment by orionz** [comment]
We just moved the automerge-rs rewrite to main.  We'll be cutting an official release soon.
