### ISSUE TITLE
Frontend: avoiding cloning the optimistic state when applying remote patches

### ISSUE THREAD

**Issue by jeffa5** [automerge/automerge-rs#226]
Currently we avoid cloning the frontend's state when only local operations occur which is a big win, however we still have the issue of cloning the reconciled state when we encounter a non-local patch:

https://github.com/automerge/automerge-rs/blob/4ce27ac18b52a33690b090f459937629374cda8c/automerge-frontend/src/lib.rs#L127-L129

This is due to the optimistic state not having updates from remote peers (fine) but not having a way to get back to the newly reconciled state. I can think of two ways to avoid this:

1. Track the updates that get applied to the remote state and have a mechanism to undo them (similar to the mutation tracker's rollback). After undoing these changes we can then apply the `checked_diff` to the state to get us to the same reconciled state.

2. Alternatively, probably a lot more work, we could alter the way that the frontend works by keeping one reconciled state and not an optimistic state. Instead, to operate optimistically we keep the changes that have been applied optimistically and when querying the document these can be used to figure out the correct operation to perform, e.g. an optimistic delete of a key can be checked for on the map object before trying to obtain it from the reconciled state. There would be quite a bit of complexity here but it would lead to a reduced memory footprint (one state instead of two) and avoids the cloning problem.

I'm currently leaning towards 1 for now as it is quicker to implement and get working while 2 represents a much larger change which should probably be done as a longer term thing.

Anyway, happy to discuss alternatives and comments :)

**Comment by alexjg** [comment]
I'm leaning towards `1` as well but I would like to bottom out what `2` would looks like. When you say we store the optimistically applied changes would we effectively be building part of the `OpSet` logic into the frontend? Do you have anything like a rough sketch of what the data structures and algorithms we would use are in your head?

**Comment by jeffa5** [comment]
So, for `2` we would have an adapted `StateTree`, something like `StateTreeRefWithOverlay` and corresponding `StateTree(Map|Table|...)RefWithOverlay`.

These new structs would track the operations applied optimistically, somewhat like how we keep a list of the operations on a `MutableDocument`, but per object.

When querying these `*Overlay`s for a value the function effectively has to build the corresponding value from the ref of the reconciled state object as well as the operations on that key. So, for a map we'd extract the key from the referenced `StateTreeMap` and then apply any operations for that key on top of it.

This adds work on each access but reduces the memory footprint, some of the work could probably be cached for repeated key accesses. I think this might share some similarities to the OpSet logic.

Though, writing this, I think `2` would also mean that we cannot apply patches directly to the reconciled state, so have to keep them around. This is because while we have an optimistic version and still outstanding changes to the backend we need to keep the optimistic state around.

Or, a `3` that adapts the ideas from `2`: have the `StateTreeRefWithOverlay` keep a mutable `StateTree` (rather than immutable), apply optimistic updates straight onto it, keeping a list of the operations just as mutable document does, then when we want to get back to the reconciled state we can just undo the changes, apply the patches we queued up and then we're all good. This is basically the same implementation of mutable document actually so may be a lot easier to implement!

**Comment by jeffa5** [comment]
I think `3` is actually just equivalent to storing the `MutationTracker` in the `FrontendState` (when we're optimistic) and updating the functionality to clear the tracked ops differently. Then the rollback is already built in.
