### ISSUE TITLE
RFC: Sorted collections

### ISSUE THREAD

**Issue by jeffa5** [automerge/automerge-rs#228]
I have a use case that requires iterating through the keys of a Map object in order. This is currently quite painful, having to extract them all, then sort them before I can use them. This can happen a lot of times, making it costly.

If we may add support for things like sets in future, should we also add support for sorted maps?

For the Rust frontend we'd need to add a new `StateTreeSortedMap` and associated `Value::SortedMap(BTree<String, Value>)` type. This would allow iteration in lexicographical order of the keys, also using the usual BTreeMap API (range etc).

However, we'd need to know when to use which internally, if we didn't want this internally then perhaps the user could tell automerge that certain paths correspond to sorted collections. This only has an effect to their local view so things like schema changes aren't affected.

If we do add support into automerge I'd imagine it either as a new type, `sorted-map` or somesuch, or a flag `sorted : bool`, I'd likely go with the former as the flag won't be relevant to any other options.

This will also need an identifier for its type in the binary encoding so that other clients know that it is a sorted map. Practically a lot of the logic would stay the same though, due to it being similar to a regular map.

What do you think @alexjg @ept ?

**Comment by alexjg** [comment]
This feels to me like it belongs exclusively in the frontend. The backend wouldn't be doing anything different for a sorted map. What it seems we really want to do is tell the frontend that data at a particular path should be treated in a particular way (i.e it should be in a `StateTreeSortedMap`, not a `StateTreeMap`).

This association of metadata with _paths_ seems to crop up a lot, I'm encountering it when trying to implement simple schema validation and access control schemes.

Anyway, I think the approach I would favour here would be to implement this purely in the frontend and have some kind of metadata that can be provided to the frontend at construction time around how to treat particular paths. How does this sound? Would this fit your usecase?

**Comment by jeffa5** [comment]
Agreed, it does seem rather frontend specific. The challenge then becomes how to make the api for this expressive enough.

I think it should be at construction time, at least for now. I can see potential use cases for adapting it at runtime with schema evolution but that might come when we do something like cambria.

I think there are a few ways this could be used:
1. give a list of specific paths that should be sorted maps if they are maps at all (fine if you know all the paths that will exist in future but not flexible enough for my use case (kv store))
2. give a path prefix under which all maps should be sorted (works well if we don't have nested maps but otherwise this may make too much a btreemap)
3. It seems like static approaches would get rather complex and involve a DSL or other complexity. Rather, a runtime alternative is to allow users to adapt the schema dynamically: `frontend.set_schema_at(path, Schema{type:Map})` or a more restricted `frontend.sort_map_at(path)`. This would store the configuration so could be called just before performing a `change` or applying changes from another peer (the user can inspect the patch).

I'm not completely sold on these as yet so I might try experiment with a few approaches in some branches and see. 

Another alternative would be to make to make the  frontend generic over a schema (`Frontend<Schema>`) and then push it to the type level and they describe the schema up front, this also gets complex though...

**Comment by jeffa5** [comment]
I'm trying things out over in this branch: https://github.com/automerge/automerge-rs/tree/frontend-sorted-map

**Comment by orionz** [comment]
Is this still relevant with the new design?

**Comment by jeffa5** [comment]
I don't think so as map keys are returned in sorted order by default anyway.
