### ISSUE TITLE
Frontend should be Send

### ISSUE THREAD

**Issue by dvc94ch** [automerge/automerge-rs#235]
quick fix would be using im instead of im_rc.

**Comment by alexjg** [comment]
We were using `im_rc` but it has some performance impacts so we switched to `im`. The basis for this is that the original design goal was for the frontend/backend split is to enable the frontend to make very fast edits on a low latency UI thread whilst the backend does the heavy lifting. In this design the frontend stays on a single thread and messages are passed to and from the backend.

However, we don't (currently) support multiple frontends for a single backend so I can imagine this is inconvenient. Do you mind if I ask what your usecase is?

**Comment by dvc94ch** [comment]
Yes, that's how I'm using it too. The problem was sending a frontend over a channel to a ui thread, but I'm sending a `SendableDocument` that doesn't have a `Frontend` which can be converted into a `Document` which contains a `Frontend`. That seems to work fine.
