### ISSUE TITLE
[C-binding] 

### ISSUE THREAD

**Issue by heckj** [automerge/automerge-rs#244]
While working on docs, I ran into the issue that Automerge has some constraints around what is a valid Actor ID and what isn't. Would it be possible to extend the C bindings to support an API call that returns if a given string is a valid Actor ID or not?

It's convenient to be able to create an Actor in the Swift API using a string literal, but it doesn't seem sensible to reproduce any constraint/error checking in the Swift API if it can be exposed from the C API.

**Comment by alexjg** [comment]
Hmm. In principle there should be no constraint here. We represent actor IDs as just sequences of bytes (although things will be much faster if you use < 128 bits). The solution the should be to figure out what part of the codebase is erroneously requiring a UUID string and relax that check.

**Comment by heckj** [comment]
Makes sense - I wasn't sure if there was an intended constraint here or not, and assumed there might be based on the debugging of the swift side of this code with @lightsprint09. 

The C binding where I hit this (although I think it's safer to assume it's core and not just this method) was
`automerge_apply_local_change(automerge, string)` - in this block from  `RSBackend.swift`:
```
    public func applyLocalChange(request: Request) -> Patch {
        let data = try! encoder.encode(request)
        let string = String(data: data, encoding: .utf8)
        let length = automerge_apply_local_change(automerge, string)
        var buffer = Array<Int8>(repeating: 0, count: length)
        automerge_read_json(automerge, &buffer)
        let patchString = String(cString: buffer)
        let patch = try! decoder.decode(Patch.self, from: patchString.data(using: .utf8)!)

        return patch
    }
```
The string that was passed in (I manually added the newlines for formatting):
```
{"startOp":1,"actor":"actor1","time":1638388597,"message":"",
"ops":[
  {"insert":false,"action":"set","obj":"_root","pred":[],"datatype":"int","value":1,"key":"x"}
],
"deps":[],"seq":1}
```

And when the function was called, the C API returned -1, which ultimately led to the crash scenario.
While debugging, @lightsprint09 asserted:
`The actorID needs to be a special format. It looks like only a UUID without the - is allowed`

Based on what you're saying, that's more hypothesis than resolution - if so, then this is a bug report about a failing call through the C API instead of a request for additional API to support exposing constraints. ;-)

**Comment by alexjg** [comment]
I'm not at a computer right now but I'm pretty sure the JSON encoding of actor IDs uses hexadecimal notation. I think this is consistent with the JS side

**Comment by ept** [comment]
See my comment here https://github.com/automerge/automerge-swift/pull/48#issuecomment-986088362

**Comment by heckj** [comment]
So it sounds like arbitrary strings can be the source - but any strings going to the backend are expected to be characters in the set of those that make up hex strings. Not much need for an API endpoint for just that then, just need to reflect it within the Swift API where we hit the crashing scenario and make sure we can't do that again.

**Comment by jkankiewicz** [comment]
> Would it be possible to extend the C bindings to support an API call that returns if a given string is a valid Actor ID or not?

FYI, I added a function to the experimental C API in #275 that generates a hexadecimal actor ID string in case one is not in the mood to guess.
