### ISSUE TITLE
[Question] Clarification on protocol

### ISSUE THREAD

**Issue by Gekctek** [automerge/automerge-rs#267]
What is the source of truth for automerge-protocol.
Im currently playing with a C# interop and am confused by how to model my requests.
Looking at the JS version of automerge docs like [BINARY_FORMAT](https://github.com/automerge/automerge/blob/main/BINARY_FORMAT.md) there are descriptins on the models like operations, but I see different model types when looking at the automerge-rs lib.rs/cs-v2. Specifically right now im trying to look at serializing Operations. The rs version has cursors and multiset, but the JS does not. Which one should I be referencing?
My guess is rs but want to make sure im not implementing towards the wrong docs.
I know things are in development and in flux so i know docs arent always up to date, just want to know where to be looking.

Question 1.5
if rs, what is the serialized version of 
```
#[strum_discriminants(name(ScalarValueKind))]
#[serde(untagged)]
pub enum ScalarValue {
    Bytes(Vec<u8>),
    Str(SmolStr),
    Int(i64),
    Uint(u64),
    F64(f64),
    Counter(i64),
    Timestamp(i64),
    Cursor(OpId),
    Boolean(bool),
    Null,
}
```
how are numbers differentiated in json?
Is there a 'type' field or is just a value that is just interpreted based on the changed object schema?

**Comment by alexjg** [comment]
There are a few things you might mean when you say "protocol" here. In the current version of automerge there's a front-end and a backend which talk to each other via a simple protoco, changes going from the front-end to the backend and patches going from the backend to the frontenl. This is the `automerge_protocol:: {Change, Patch}` types. There's not really a specification for this anywhere. However, we're planning to do away with this front-end/backend split - more details on that [here](https://github.com/automerge/automerge-rs/pull/265#issuecomment-1021242285).

There's also the storage format for automerge documents. This is used for compactly saving documents and for transferring them over the network. I have a work in progress specification for this format [here](https://alexjg.github.io/automerge-storage-docs/)

**Comment by Gekctek** [comment]
I'll watch for those new changes. Thank you
