### ISSUE TITLE
Suggestion (not a feature request): Take a look at Replicated Object Notation (RON)

### ISSUE THREAD

**Issue by ckaran** [automerge/automerge-rs#28]
I'm deliberately duplicated my comment in https://github.com/automerge/automerge/issues/266 here.  If this suggestion isn't helpful, please close it immediately.

This is just a suggestion, not a feature request. You might want to look at [Replicated Object Notation (RON)](https://replicated.cc/). It might be helpful (or not; I stumbled across this project by accident, it just looks like RON might be useful to it).

**Comment by alexjg** [comment]
I'll defer to @ept's response on that issue. This repo is focused on implementing the changes Martin references in that issue.
