### ISSUE TITLE
Tree traversal

### ISSUE THREAD

**Issue by jeromegn** [automerge/automerge-rs#335]
I'd love more features for traversing the tree efficiently by `ObjId`.
- Being able to iterate children and ancestors of an object
- When iterating on keys (if that stays) -> using a more memory-efficient `type Item` for the iterator (currently this is a `String`).
- Support something like [JSONPath](https://www.rfc-editor.org/in-notes/internet-drafts/draft-ietf-jsonpath-base-04.html) or [JSON Pointer](https://datatracker.ietf.org/doc/html/rfc6901)s

Here's our use-case:
- Server-side only (not that it matters too much here)
- Can observe any "json path" for changes within itself or its any of its children
- Notifies of changes, including the relative path to the change + the new value as JSON

The `Patch` API (in `experiment`) works pretty well for this, except traversal feels costly (I haven't profiled it) and I constantly have to allocate strings when building relative paths.

Things I tried or intend to try:
- Keep our own internal tree structure up to date. This allows us to traverse it more efficiently, but it's a pain to keep in sync.
- Lazily cache `ObjId`'s children and ancestors for faster traversal
- Not care about any of this until it becomes a big problem. I foresee this being a problem because I want it to be possible to watch the root `ObjId` for any changes.

**Comment by ept** [comment]
Being able to query the ancestors of an object would also be useful for the JS API (because when an object is updated, it needs to make a new immutable copy of all the objects on the path from the root to the updated object).

**Comment by jeromegn** [comment]
This is largely fixed for us with the `Parents` iterator.
