### ISSUE TITLE
Efficient multiple documents synchronization

### ISSUE THREAD

**Issue by jeromegn** [automerge/automerge-rs#336]
Is there a way to efficiently synchronize `n` documents?

The current way to do it seems to be to just use `generate_sync_message` and `receive_sync_message` for every document, possibly in parallel.

I've heard there might be a better way though! I'd love to hear about it.

**Comment by ept** [comment]
At the moment the sync is per-document; you can sync multiple documents over the same connection by running a separate sync on each document and tagging each message with the ID of the document to which it pertains.

I am planning to write up a proposal for a "repository" abstraction that would handle storage and sync of a collection of documents, but I haven't got round to it yet.

**Comment by jeromegn** [comment]
Sounds good. I'm going to synchronize them over http/2 which should multiplex quite well.
