### ISSUE TITLE
[C-Interface]How to access getChanges

### ISSUE THREAD

**Issue by lightsprint09** [automerge/automerge-rs#35]
The JS Implementation provides [getChanges(oldState: BackendState, newState: BackendState): Change[]](https://github.com/automerge/automerge/blob/main/%40types/automerge/index.d.ts#L168). I don't know how this is exposed in the C-Interface.

**Comment by zeeyang** [comment]
I'm interested in this as well. Is this something the backend will support or should it be implemented in frontend by comparing vector clock.

**Comment by orionz** [comment]
that function call internally does a `getChanges(oldState, getHeads(newState))` - I noticed that getHeads was recently added to the js implementation but was not implemented in the C API - I've added support for that in the last patch.   Not tho that this strategy is insufficient if new and old state have diverged - Martin talks about this [here](https://github.com/automerge/automerge/issues/290) and some new API calls will be added soon to address this.

**Comment by orionz** [comment]
Commit fixing this issue is here

https://github.com/automerge/automerge-rs/commit/78024fd000cee8239b7ba72b99f9fd1e47df05c7
