### ISSUE TITLE
Using automerge-wasm with JS bundler

### ISSUE THREAD

**Issue by ept** [automerge/automerge-rs#367]
I wanted to try updating [crdt-benchmarks](https://github.com/dmonad/crdt-benchmarks) to use automerge-wasm, and ran into some problems using the wasm npm package. The benchmarks use ES6 imports, and [rollup](https://rollupjs.org/guide/en/) to bundle all the JS into one file. Maybe it would be possible to change them not to use a bundler, but I thought that it's likely that lots of other people will also want to use Automerge with a bundler, and so we need to figure out how to support Wasm in that context.

Here's a minimal setup I used to test Automerge-wasm with Rollup. `package.json`:

```js
{
  "name": "benchmark-automerge-wasm",
  "main": "./run.js",
  "type": "module",
  "dependencies": {
    "automerge-wasm": "^0.1.2",
    "rollup": "^2.72.0"
  }
}
```

`run.js`:

```js
import init, { create, load } from 'automerge-wasm'

init().then(_ => {
  let doc = create()
  let text = doc.putObject('/', 'text', 'hello')
  console.log(doc.text(text))
  doc.free()
})
```

`rollup.config.js` (simplified config from [crdt-benchmarks](https://github.com/dmonad/crdt-benchmarks/blob/main/js-lib/rollup-helper.js)):

```js
import nodeResolve from '@rollup/plugin-node-resolve'
import commonjs from '@rollup/plugin-commonjs'

export default [{
  input: './run.js',
  output: {
    file: './dist/benchmark-browser.js',
    format: 'es',
    sourcemap: true
  },
  plugins: [
    nodeResolve({
      mainFields: ['module', 'browser', 'main']
    }),
    commonjs()
  ]
}, {
  input: './run.js',
  output: {
    file: './dist/benchmark-node.js',
    format: 'es',
    sourcemap: true
  },
  plugins: [
    nodeResolve({
      mainFields: ['module', 'main']
    }),
    commonjs()
  ],
  external: ['isomorphic.js']
}]
```

Put those three files in the same directory, `npm install` then run `rollup -c`, which generates `dist/benchmark-node.js` and `dist/benchmark-browser.js`.

Try running `dist/benchmark-node.js`, which complains that `ReferenceError: fetch is not defined`. Okay, looks like it's using the browser version rather than the node version of the wasm package.

Tried changing the import to `automerge-wasm/nodejs` and re-ran `rollup -c`. Now on running `benchmark-node.js`, the error is: `ReferenceError: __dirname is not defined in ES module scope`. Ugh. Rollup is generating ESM and that doesn't play nicely with the code generated by wasm-bindgen.

I hacked `benchmark-node.js` and manually replaced the occurrence of `__dirname` with a hard-coded path. Also manually copied `node_modules/automerge-wasm/nodejs/bindgen_bg.wasm` to `dist/` because Rollup didn't know that the file needs to be copied. Now I get the following error:

```
panicked at 'could not retreive random bytes for uuid: Node.js crypto module is unavailable', /home/orion/.cargo/registry/src/github.com-1ecc6299db9ec823/uuid-0.8.2/src/v4.rs:31:13
```

Looks like Wasm needs to call back into Node libraries in order to generate random UUIDs, which makes sense given Wasm doesn't have a random number API, but at this point I'm stuck because I have no idea why the crypto module isn't getting wired up automatically.

Next, I tried my luck with the browser version. Changed the import back to 'automerge-wasm' and made the following minimal HTML file:

```html
<!DOCTYPE html>
<script type="module" src="./dist/benchmark-browser.js"></script>
```

Fired up `python3 -m http.server` (because Wasm has to be served over HTTP, it can't be loaded from a local file, why???) and loaded the HTML file in a browser. It managed to fetch the wasm file and call the `init` function, but threw the following exception before the promise returned by `init()` resolved:

```
TypeError: WebAssembly.instantiate(): Import #0 module="__wbindgen_placeholder__" error: module is not an object or function
```

Here again I am stuck…

**Comment by ept** [comment]
If I change the Node section of the Rollup config to `format: 'cjs'`, delete the line `"type": "module"` from `package.json`, import `'automerge-wasm/nodejs'`, and then run `rollup -c && dist/benchmark-node.js`, I can skip the `__dirname` hackery and jump straight to the uuid-related panic.

**Comment by orionz** [comment]
I gave this a try.  I found a workaround.  The import seems to be happening at the wrong level.  I took a plain checkout of the repo and added 

```js
import * as Automerge from "automerge-wasm"
let doc = Automerge.default.create()
```
And that seemed to work fine,  For whatever reason the default import is being imported as the sub property `default` ...
I'll see if I can figure out a fix at the packaging level but this should allow you to update the benchmark

**Comment by orionz** [comment]
Note the `init()` isn't needed b/c it seems to be importing the node/commonjs version

**Comment by ept** [comment]
The code you posted works if no bundler is used, but if I push that code through Rollup, the result still isn't runnable (I get the exception `TypeError: init.create is not a function`). Messing around with the code a bit takes me back to the same exceptions as before.

**Comment by orionz** [comment]
Im messing around with rollup and finding it really fussy - I dont think theres any way to make it work cleanly with wasm anyway - I added very simple boiler plate webpack to packing `automerge-wasm` into similar bundles - perhaps the correct path is to use a different bundler for this part 

https://github.com/automerge/automerge-rs/pull/369

I'll keep fiddling with rollup and see if I can feed it the right set of plugins to work

**Comment by orionz** [comment]
The conclusion seems to be rollup wont play nicely with the code output from `wasm-bindgen` but webpack works great.  If someone figures out a workaround for rollup let me know but otherwise i recommend people use webpack for this.  (example code has been added)
