### ISSUE TITLE
Free wasm memory automatically

### ISSUE THREAD

**Issue by ept** [automerge/automerge-rs#378]
The current API exposed by automerge-wasm requires users to manually call `.free()` on a document when it is no longer needed, as otherwise the memory allocated for that document within the Wasm module will leak. However, [most modern browsers](https://caniuse.com/mdn-javascript_builtins_finalizationregistry) now support [FinalizationRegistry](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/FinalizationRegistry) and [WeakRefs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakRef), which [could be used](https://stackoverflow.com/questions/65966924/how-to-ensure-wasm-memory-is-freed-when-using-it-from-javascript) to automatically free Wasm memory when the corresponding JS object is garbage-collected.

I could imagine two ways of doing this: either writing our own JS code that registers each document object with the FinalizationRegistry and calls `.free()` when deallocated, or letting wasm-bindgen auto-generate this code using the [`--weak-refs` command line option](https://rustwasm.github.io/wasm-bindgen/reference/weak-references.html). Apparently, [wasm-pack does not yet support this option](https://github.com/rustwasm/wasm-pack/issues/930), so we would have to call wasm-bindgen directly. I don't understand the build tooling well enough to know how to set this up.

I found [this issue](https://github.com/iotaledger/identity.rs/pull/694) in which another project added weak-refs support to their Rust-Wasm project, and it looks like there are some gotchas. In particular, that issue points out that there is a [bug in wasm-bindgen](https://github.com/rustwasm/wasm-bindgen/pull/2677) when generating code of the form `ptr = 0`, and our bindgen-generated wrapper currently contains that pattern in `exportSyncState` and `encodeSyncState`.

**Comment by alexjg** [comment]
This is now supported. We use `wasm-bindgen` directly to avoid the problems with `wasm-pack` and I'm pretty sure the UAF bug is fixed by [4458587c50291a933e808bf75125fb4ed5fb5eed](https://github.com/rustwasm/wasm-bindgen/commit/4458587c50291a933e808bf75125fb4ed5fb5eed)
