### ISSUE TITLE
AMClone missing from C-API

### ISSUE THREAD

**Issue by lightsprint09** [automerge/automerge-rs#383]
Either AMClone is not implemented or it is missing from the header file. Maybe @jkankiewicz can help?

**Comment by jeffa5** [comment]
I've now made it so that these get built as part of the docs workflow and published (though not directly linked to), available at https://automerge.org/automerge-rs/automerge-c/

This will keep up with the main branch

**Comment by jkankiewicz** [comment]
> Thanks @jkankiewicz for the instructions!

@jeffa5, you're welcome!
Thank you for integrating the building and publishing of the C API documentation into your CI workfow! Now that people around the world can read it without having to build it themselves I'd better scan it again for any remaining errors and omissions.

BTW, I first provided a version of those instructions in PR #275.

**Comment by jkankiewicz** [comment]
@lightsprint09, is `AMdup()` the function you're looking for? If so, please close this ticket. Thanks!

**Comment by jkankiewicz** [comment]
> Either AMClone is not implemented or it is missing from the header file.

@lightsprint09, since I've relented and renamed `AMdup()` to `AMclone()` through #410 can you please close this ticket?
