### ISSUE TITLE
`parent_object` doesn't work for scalar values

### ISSUE THREAD

**Issue by jeromegn** [automerge/automerge-rs#388]
I think this used to work but doesn't anymore.

I modified a test to show this:

```rust
#[test]
fn get_parent_objects() {
    let mut doc = AutoCommit::new();
    let map = doc.put_object(ROOT, "a", ObjType::Map).unwrap();
    doc.put(&map, "foo", "bar").unwrap();
    let (_, scalar) = doc.get(&map, "foo").unwrap().unwrap();
    let list = doc.insert_object(&map, 0, ObjType::List).unwrap();
    doc.insert(&list, 0, 2).unwrap();
    let text = doc.put_object(&list, 0, ObjType::Text).unwrap();

    assert_eq!(doc.parent_object(&map), Some((ROOT, Prop::Map("a".into()))));
    assert_eq!(doc.parent_object(&list), Some((map.clone(), Prop::Seq(0))));
    assert_eq!(doc.parent_object(&text), Some((list, Prop::Seq(0))));
    assert_eq!(
        doc.parent_object(&scalar),
        Some((map, Prop::Map("foo".into())))
    );
}
```

The last assertion fails, the return value of `doc.parent_object(&scalar)` is `None`.

**Comment by jeromegn** [comment]
This might be my bad!

Maybe this was only ever intended to work for `Value`s that are `ObjType`?

**Comment by jeffa5** [comment]
I would only expect it to work for actual object ids, not just any reference to an op (which is what the scalar is in this example).

**Comment by orionz** [comment]
> This might be my bad!
> 
> Maybe this was only ever intended to work for `Value`s that are `ObjType`?

That was the intention.  It is possible to embed enough info with a value that this query could work but would add some overhead.  My though would just be to change the api call to either only take ObjId's as an argument or return a useful error `cannot retrieve parent object from a scalar value` or something.

**Comment by jeffa5** [comment]
At the moment I think the only IDs we return are (type wise) exids, which don't differentiate between objid or opid. Might be worth exploring ways of differentiating these.

I think a proper error message is definitely worth it though, my fault for not adding one!
