### ISSUE TITLE
Uncaught TypeError: 'ownKeys' on proxy: trap returned duplicate entries

### ISSUE THREAD

**Issue by rf-** [automerge/automerge-rs#396]
This is another case where a doc ([attached](https://github.com/automerge/automerge-rs/files/9006532/automerge_data_2.gz)) triggers an error in automerge-js that doesn't happen in upstream Automerge:
``` javascript
const Automerge = require('automerge-js');
Automerge.use(require('automerge-wasm'));

const doc = Automerge.load(require('fs').readFileSync('automerge_data_2'));

console.log(Object.entries(doc.versions['70d4809a163446aaa91db8c5795e955e'].grid.cells));

// Uncaught TypeError: 'ownKeys' on proxy: trap returned duplicate entries
//    at Function.entries (<anonymous>)
```

Nothing seems obviously weird about the data in this part of the doc tree I don't think?

**Comment by orionz** [comment]
Thank you for finding this...  a fix is in automerge-js 0.1.8
