### ISSUE TITLE
Docs workflow failing

### ISSUE THREAD

**Issue by jeffa5** [automerge/automerge-rs#398]
The docs workflow is failing on main, seems to be an issue finding cmocka which was removed in https://github.com/automerge/automerge-rs/commit/4f7843e00739c58d22a7bb510968037bc256bd04, @jkankiewicz should cmocka be removed from somewhere else or added back into the workflow?

**Comment by jkankiewicz** [comment]
@jeffa5 , AFAIK, no changes to the C API have been pushed for weeks and building the "automerge-c" library will never again have an indirect dependency upon the cmocka library..

The workflow must have built it with an old version of CMakeLists.txt.

**Comment by jeffa5** [comment]
The script was still building the `automerge-c` tests with cmake which was dragging in cmocka, I've made the docs build not build the tests so avoiding the cmocka dep now.
