### ISSUE TITLE
`automerge-js` 0.1.4 and 0.1.5 contain incorrect TypeScript definition file

### ISSUE THREAD

**Issue by rf-** [automerge/automerge-rs#399]
I'm not sure what the cause of this is, but 0.1.2 had the same issue before @orionz pushed a fix in 0.1.3. It seems like `index.d.ts` is generated in the wrong format, causing `tsc` to complain when typechecking code that imports from the package:
```
src/windows/main/renderer.tsx:12:28 - error TS2306: File 'node_modules/automerge-js/index.d.ts' is not a module.

12 import * as Automerge from "automerge-js";
                              ~~~~~~~~~~~~~~
```

**Comment by orionz** [comment]
We keep running into issues with the default export - im going to package the fix you had in your PR but on the next release im going to change the default export to be a normal export named "init"

**Comment by orionz** [comment]
This should be fixed in the latest release - please let me know if you run into any more issues.

**Comment by rf-** [comment]
I’ll check it out, thanks!

**Comment by orionz** [comment]
make sure to use 0.1.8 - i found a problem with 0.1.7

**Comment by rf-** [comment]
Looks good, thanks again :+1:
