### ISSUE TITLE
Speed Comparisons Between Automerge Implementations

### ISSUE THREAD

**Issue by adorsk** [automerge/automerge-rs#41]
Firstly, thanks for making this rust port!

What follows below is not meant to be critical, more just an FYI to folks who are considering using the wasm backend right now.

I recently ran into an issue in an Automerge project where it was taking a long time to apply changes to larger Automerge documents (4+ seconds per change, for a doc of ~2MB size).

This project was using the current 'main' branch of Automerge (not the performance branch)

I wondered if switching to the Automerge performance branch + wasm backend might help speed up the updates.

Before doing the full switch, I made a small spike script to compare the speed of updates w/ different automerge versions/backends. My spike script is here: https://gist.github.com/adorsk/3011ceb830a73d138fcc48f2e57775ad . It's a bit hacky, and requires manually installing the different versions of automerge).

The good news is that I found that the wasm backend was usually faster. However, the bad news is that it wasn't always significantly faster. Depending on the type of change operations, the speed-ups I saw were at most 2x faster than the current 'main' Automerge branch.

This certainly shouldn't be taken as an authoritative result, since it's just using my hacky little benchmarking script.

But just a caveat to let folks know that speed improvements may be modest. I hope that this is helpful! And again, thanks for making this implementation, so that it's even possible to do comparisons like this.

-----
Note to future readers who find this later: there are a number of things in-progress which may improve speed: https://github.com/automerge/automerge/issues/300 , both in the rust and javascript Automerge implementations. So do check back later.

**Comment by orionz** [comment]
Hey there.  I haven't been doing many performance comparisons between the main branch and the performance branch.  From my vague recollection in some tests the two implementations trade blows, performance losing as often as its winning, but in other cases, especially large documents and long lists the difference is extreme.  The most important difference is that the performance branch uses 100x less memory and its change format is about 100x smaller.  There's performance test [here](https://github.com/orionz/automerge-perf) with a complex document that I benchmark against.   The performance branch in one run the performance branch finishes in 55s, the wasm finishes in 10s and the `main` version never finishes or exhausts ram.  From the memory usage alone I see the main implementation is being a dead end.  We're pushing to get performance released for production ASAP.  There are still some tweaks to be made to make sure everyone has a good experience.  I was surprised to see your benchmark only get a 2x boost on the WASM.  I ran them just to confirm.  For most of the benchmarking I've done I find the wasm is generally 5x to 10x faster, tho there are some cases where I've seen it only match the speed of the js implementation.  We can obviously do better and are making a big performance push right now.

**Comment by adorsk** [comment]
Thanks for letting me know about your https://github.com/orionz/automerge-perf repo, I hadn't seen that.

I wish I knew more about how document schemas/sizes affect operation throughput. I haven't done any in-depth profiling yet to try and figure that out. Might be interesting to make a 'document zoo', with different sizes/shapes of documents to run through benchmarks. (or maybe something like that already exists?).

In any case, thanks for the info about your performance tests, that is helpful to know. I'm looking forward to seeing how the columnar backend performs too once it's ready.

I'll close this discussion for now, but if I do any future benchmarking stuff, I'll re-open here.

**Comment by gmrigna** [comment]
@adorsk Sorry for writing this here but I haven't found any other way... I am actually trying to send you an email about the OPTIMADE API to which you contributed (in Leiden in 2016). We are finalizing a paper of which I believe you should be a co-author.
