### ISSUE TITLE
Rust API which is closer to JS API

### ISSUE THREAD

**Issue by gyzerok** [automerge/automerge-rs#426]
Hello everyone!

I am currently building a collaborative app and am diving into CRDTs. Through extensive googling I've found automerge and am excited by the work you've been doing. This is truly impressive.

Haven't used your library yet and was just looking through examples. The rest of the issue is just my personal take on the API. With this issue I have no intention to undermine the work you are doing (am still thinking it's amazing), just want to bring some possible adopter perspective. Basically the way API is done is sort of pushing me away from using it. But let me explain and please bare with me.

In the JS version we are actually (sort of) mutating fields in place and the library by itself is generating us the correct diff. The ergonomics of this API reminds me https://github.com/immerjs/immer which works nicely with TypeScript and allows you to keep your manipulations type-safe. It also allows you to work on your data as-is. In my opinion these properties of the API are very useful in terms of maintainability and DX.

On the other hand in Rust we have to use strings for field names, which, from my perspective, makes using Rust API less type-safe and ergonomic.

What if we could maintain the API in Rust as well? So something like the following could be possible.

```rust
struct Document {
  cards: Vec<Card>
}

struct Card {
  text: String,
  done: bool
}

let mut doc_root = Automerge::new(Document { cards: Vec::new() });

doc_root.transact_with::<_, _, AutomergeError, _, ()>(
  |_| CommitOptions::default().with_message("Add card".to_owned()),
  |doc: &mut Document| {
    doc.cards.push(Card { text: "hello".to_owned(), done: false });
    Ok(())
  },
)
.unwrap();

doc_root.transact_with::<_, _, AutomergeError, _, ()>(
  |_| CommitOptions::default().with_message("Mark card as done".to_owned()),
  |doc: &mut Document| {
    doc.cards[0].done = true;
    Ok(())
  },
)
.unwrap();
```

This API looks very much like JS one. However the problem is - how do we calculate the diff then?

Here I am wondering if we could serialize the structure at the beggining of the transaction to JSON, then serialize it at the end of the transaction and then calculate the diff between two. I assume it could be done by writing a function which calculates the smallest possible diff between 2 JSONs in a way that should be structured in terms of automerge.

The only concern I can see here is inefficiency due to extra serializations. Maybe I am missing something else? I am also not that experienced in Rust, so maybe what I am proposing is completely undoable 🤷🏻‍♂️ 

How does this idea sound to you?

**PS:** By the way have been reading Designing Data-Intensive Applications and the book is an incredible source of knowledge!

**Comment by gyzerok** [comment]
Thank you for the response!

It seems like I've got an incorrect idea of what Rust library is supposed to be. Now it makes perfect sense and I totally get it. The effort you mentioned from the first glance does indeed look like something I am talking about. Hope some more higher-level wrapper will emerge.

In the meantime I'll try to dig a bit deeper and see what I can achieve. Definitely don't want to invent a wheel here and would love to use the CRDT itself.

Love the effort and wish you success in proceeding further!

**Comment by satvikpendem** [comment]
For what it's worth I'm thinking of using automerge-rs and was looking for exactly this feature, having typed struct support rather than string keys. There are a lot of higher level apps being built on Rust these days, such as webservers like what I'm making, so it would be nice to have a similar high level API like the JS version.

**Comment by alexjg** [comment]
I should have posted this here before but I'm currently working on https://github.com/alexjg/autosurgeon which addresses this I think, please let me know what you think.

**Comment by satvikpendem** [comment]
Awesome, let me use it and report back.
