### ISSUE TITLE
Some editing traces are incredibly slow

### ISSUE THREAD

**Issue by josephg** [automerge/automerge-rs#431]
I've been preparing some benchmarks for a followup to my [blog post](https://josephg.com/blog/crdts-go-brrr/) last year.

Its mostly working ok, but one of my [testing data sets](https://github.com/josephg/crdt-benchmarks) is replayed extremely slowly (160 seconds to process 40k edits):

```
# These two are OK
Processed 259778 edits in 386.366044ms
Written automerge-paper.am (129090 bytes)
Processed 137993 edits in 616.052523ms
Written seph-blog1.am (204999 bytes)

# This is just, whoa.
Processed 40173 edits in 110.201298005s
Written rustcode.am (209159 bytes)

# And this is pretty slow too
Processed 19749 edits in 3.769206113s
Written sveltecomponent.am (61396 bytes)
```

I made a self contained project repo to reproduce the problem:

https://github.com/josephg/am-slow-repro

Just `cargo run` to see.

Its using automerge-rs from cargo. I see the same behaviour in the latest git main as well, though performance improves from 160s to 110s going from the cargo version -> the `main` branch here.

**Comment by alexjg** [comment]
Thanks for running these! I'm neck deep in javascript packaging issues this week but next week I'll do some investigating.

**Comment by alexjg** [comment]
Could you give this a try with `automerge@0.3.0`, this takes ~1 second for me.

**Comment by josephg** [comment]
Yep looks good now. No idea what the problem was, but it looks like its been fixed! (And congratulations on the release! 🎉)

```
automerge-paper:
  Processed 259778 edits in 211.377667ms
  Written automerge-paper.am
  Filesize 126.06 KiB
rustcode:
  Processed 40173 edits in 626.627708ms
  Written rustcode.am
  Filesize 204.26 KiB
sveltecomponent:
  Processed 19749 edits in 87.295334ms
  Written sveltecomponent.am
  Filesize 59.96 KiB
seph-blog1:
  Processed 137993 edits in 242.237166ms
  Written seph-blog1.am
  Filesize 200.19 KiB
```

**Comment by mweidner037** [comment]
@alexjg Some more info about the slow trace above:
- If I simulate live collaboration by calling `getChanges` after every op, processing the trace becomes much slower: 327 sec for the first 100,000 ops.
- `applyChanges` is also slow (267 sec for first 100,000 ops).
- I'm using Node v18.15.0 on Ubuntu Linux.
- These numbers are for the latest version (2.0.3-marks-prelease.1), but I noticed similar behavior on 2.0.2 with Node 16.13.1 and for older `@automerge/automerge` versions (all x.x.x versions IIRC).
- Profiling shows that most of the time is spent in WASM code, so I don't think it's from the JS wrapper doing extra work: 
![image](https://user-images.githubusercontent.com/17693586/233666381-10f59b4b-3414-4297-9915-8e07f57ea3cd.png)
