### ISSUE TITLE
Mismatched heads hashes on documents with javascript numbers

### ISSUE THREAD

**Issue by adamhjk** [automerge/automerge-rs#47]
Hello! It appears that some documents fail with a `Mismatched heads hashes` when sent from a rust Backend to the javascript library that include numbers. 

For example:

```
{ "number": 1 }
```

Will fail, but:

```
{ "number": "1" }
```

Will succeed.

[A repository with a reproduction is at adamhjk/automerge-mismatched-hash](https://github.com/adamhjk/automerge-mismatched-hash).

**Comment by vedantroy** [comment]
Confirming this fails with using both `main` branches (js = fcee822dc60034c3350c031d27774cf4d2bb0fd2, rust = 7a08c52dac10452f071289c4ae0ef3ffef2fd25c).

**Comment by ept** [comment]
Will this be fixed by #128 (automerge/automerge#371)?

**Comment by jeffa5** [comment]
@vedantroy should this be fixed as of https://github.com/automerge/automerge-rs/pull/152 did you have a setup to check?
