### ISSUE TITLE
Should increment_by take an i32?

### ISSUE THREAD

**Issue by jeffa5** [automerge/automerge-rs#48]
https://github.com/automerge/automerge-rs/blob/c103b0638e24076e6cd755f102f3c75926c25d51/automerge-frontend/src/mutation.rs#L55-L56

The comment on the `increment_by` function indicates that we should be able to pass a negative value but it uses a u32 (so does the associated `LocalOperation`).

Should this simply be an i32 instead, or maybe even an i64 since that is what the `Counter` type contains?

**Comment by alexjg** [comment]
Good spot. I'll update this in the coming week.
