### ISSUE TITLE
Python

### ISSUE THREAD

**Issue by bokolob** [automerge/automerge-rs#502]
Hello.
It seems that automerge-py is stale and event doesn't compile now. Are there any plans for support python? Maybe through  automerge-c ?

**Comment by alexjg** [comment]
There has been some work done in #435 but as you will see from my response to that PR I think more work would be needed. There's no one currently working on this that I'm aware of. Certainly `automerge-c` would be one way of achieving it but I think the approach in #435 using [maturin](https://github.com/PyO3/maturin) is probably much more maintainable given that the implementation of automerge is in Rust.
