### ISSUE TITLE
Possible bug in WASM backend

### ISSUE THREAD

**Issue by eugene-eeo** [automerge/automerge-rs#53]
Hi,

I'm a student working with @ept, and my project is about measuring CRDT performance. As far as I understand, there are two ways of generating an encoded operation with Automerge:

1. **Method 1:** this was suggested in the Automerge README:
    ```js
    let new_doc = Automerge.change(doc, () => { /* ... */ })
    Automerge.getChanges(doc, new_doc)
    ```
2. **Method 2:** digging into the source code a bit, we see that `Automerge.change` is just sugar for:
    ```js
    let [new_doc, change] = Automerge.Frontend.change(doc, () => { /* ... */ })
    Automerge.encodeChange(change)
    ```

I wrote a little script (https://gist.github.com/eugene-eeo/cbe85d83e9a0bf3c5e7ddda3481803c0) that measures the performance difference between those two methods. Note that I do not just measure time required to apply and encode changes (local), but also the time required to apply those changes on another document (remote). On my machine, without the WASM backend there is quite a big difference:

```
Method 1:
local: 2068.88 ms
remote: 307.84 ms
local: 1823.04 ms
remote: 252.80 ms
local: 1623.03 ms
remote: 218.70 ms
local: 1620.21 ms
remote: 242.04 ms
local: 1619.00 ms
remote: 220.40 ms

Method 2:
local: 801.65 ms
remote: 307.96 ms
local: 590.28 ms
remote: 243.93 ms
local: 442.30 ms
remote: 228.21 ms
local: 413.66 ms
remote: 200.77 ms
local: 412.88 ms
remote: 202.48 ms
```

Notice that remote performance stays largely the same.
However when the WASM backend is used, remote performance suffers:

```
Method 1:
local: 438.06 ms
remote: 70.19 ms
local: 367.26 ms
remote: 68.41 ms
local: 329.03 ms
remote: 63.91 ms
local: 313.60 ms
remote: 63.49 ms
local: 306.28 ms
remote: 61.29 ms

Method 2:
local: 313.25 ms
remote: 966.28 ms
local: 221.59 ms
remote: 939.10 ms
local: 189.73 ms
remote: 938.31 ms
local: 173.63 ms
remote: 981.85 ms
local: 165.58 ms
remote: 930.15 ms
```

Increasing the length to something like 5k makes my computer run out of memory (using the WASM backend).

I'm using commit `a27dd61e2406e9047f68d4e3209f80b78d8d1451` for the automerge repo, and `83145b82c49809aaccf7e6463e164de59225045d` for automerge-rs.

**Comment by alexjg** [comment]
This is most likely to do with the fact that `Automerge.Backend.encodeChange` has to serialize the change to JSON before passing it to the WASM backend to encode. I believe this shouldn't be a problem in practice, the reason being that I'm not sure it's quite accurate to say that `Automerge.change` is sugar for 

```
let [new_doc, change] = Automerge.Frontend.change(doc, () => { /* ... */ })
Automerge.encodeChange(change)
```

This is true if you're using the javascript backend, as the `encodeChange` step is called in `Backend.applyLocalChange`. However, if you're using the WASM backend the `encodeChange` will happen in the WASM process and so the code is not equivalent, specifically the encoding will go directly from in memory WASM structures to the binary encoding and thus not requiring allocating a giant JSON string.

**Comment by eugene-eeo** [comment]
I see, I guess I should stick to the `Automerge.getChanges` API then, at least for the WASM version?
