### ISSUE TITLE
Can't  found any method to apply the Undo / Redo ?

### ISSUE THREAD

**Issue by vedon** [automerge/automerge-rs#58]
pub fn undo_stack(&self) -> Vec<Vec<UndoOperation>> {
        self.internal_undo_stack
            .iter()
            .map(|ops| ops.iter().map(|op| self.actors.export_undo(op)).collect())
            .collect()
    }
    pub fn redo_stack(&self) -> Vec<Vec<UndoOperation>> {
        self.internal_redo_stack
            .iter()
            .map(|ops| ops.iter().map(|op| self.actors.export_undo(op)).collect())
            .collect()
    }

what should I do with the UndoOperation?

**Comment by alexjg** [comment]
Where are you seeing this code? Undo isn't currently implemented in either the Rust or Javascript codebases (for the upcoming `1.0` release that is, older versions of the javascript codebase do implement it). We'll be planning to add APIs for it down the road.

**Comment by vedon** [comment]
Sorry, I have found the version is 0.0.1 .
