### ISSUE TITLE
CI for ensuring `no_std` compatibility

### ISSUE THREAD

**Issue by alexjg** [automerge/automerge-rs#67]
I've been using [this method](https://blog.dbrgn.ch/2019/12/24/testing-for-no-std-compatibility/) to make sure that `automerge-backend` and `automerge-protocol` build in a `no_std` environment. This is a little tricky to get working with cargo workspaces so I haven't automated it yet but we should. I think what we would need to do for this to work in CI is to create a new project at test time which sits outside of the workspace root and references `automerge-backend` and `automerge-protocol` by path.

**Comment by orionz** [comment]
Is this still something we want in the new main branch?
