### ISSUE TITLE
Update encoding/decoding logic to use *64 rather than *size

### ISSUE THREAD

**Issue by jeffa5** [automerge/automerge-rs#70]
This ensures we have consistent behaviour across 32bit and 64bit environments.

**Comment by jeffa5** [comment]
Actually, I'm not sure whether we should actually use *32 so that things like `Vec` can be ensured to work on 32 bit targets.

**Comment by orionz** [comment]
Im pretty sure - everywhere we use usize its as an index to a vector and thus usize makes sense.   I would expect a 32bit machine running automerge to break on more than MAX_INT ops or changes etc (but also run out of memory before then).
