### ISSUE TITLE
Persistent backend

### ISSUE THREAD

**Issue by jeffa5** [automerge/automerge-rs#77]
I've had a little play around with creating a persistent backend in Rust [here](https://github.com/jeffa5/automerge-persistent) and it seems to be pretty simple, thanks mainly to [this](https://github.com/automerge/automerge/issues/331) discussion.

I've created an initial `sled` implementation of this backend for persistence but aim to add some more as we go.

Any thoughts/reviews on this would be appreciated!

(feel free to close this whenever too, this is more of a notification than an issue)

**Comment by alexjg** [comment]
This is good stuff. One thing that occurs to me is that it's very common to have many documents with some kind of identifier for the document. Maybe it's worth baking that into the `PersistentBackend` by adding a generic document ID parameter to the various methods on it.

**Comment by jeffa5** [comment]
I think I'd imagine most of that being handled in a `Persister` so the `PersistentBackend` doesn't know about it. Maybe some sort of `MultiPersistentBackend` struct which handles these identifiers and operates on `PersistentBackend`s internally. Then people don't pay the complexity for multiple documents when they only want one.

**Comment by jeffa5** [comment]
Now that `apply_changes` is called internally in `receive_sync_message` we need some mechanism (likely a callback) to be able to interact with changes before they get applied to the backend. See [discussion here](https://github.com/automerge/automerge/pull/339#issuecomment-824687277) also.

**Comment by jeffa5** [comment]
This should be fixed here https://github.com/automerge/automerge-rs/pull/116
