### ISSUE TITLE
[Question] Should structuredClone objects be supported?

### ISSUE THREAD

**Issue by Jimmy89** [automerge/automerge-rs#915]
I was playing around with (overwriting) objects within automerge documents.
To avoid any issues with object references, I used `structuredClone(object)`.
I found out that structuredClone does not inherit the prototype of an object and therefore fails [this check](https://github.com/automerge/automerge/blob/4999578a7ca138e59efa12a90a1dd9380472e9f1/javascript/src/proxies.ts#L168)

I'm wondering whether this is intended behavior (implying you cannot use structuredClone) or that an additional check must be added.

**Comment by alexjg** [comment]
That is not intentional and I think we would like to support `structuredClone`, although I'm not sure what check we could do there instead. Any thoughts?

**Comment by steida** [comment]
@alexjg I would use `Object.prototype.toString.call(value) === '[object Object]';`

https://www.zhenghao.io/posts/js-data-type
